import type { MDXComponents } from 'mdx/types';
import {
  Callout,
  Card,
  CardGrid,
  CodeBlock,
  Collapser,
  CollapserGroup,
  Column,
  Grid,
  Heading,
  Link,
  List,
  ListItem,
  Popover,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableHeaderCell,
  TableCell,
  Tabs,
  Tab,
  TabList,
  TabPanel,
} from '@roadlittledawn/docs-design-system-react';
import { CodePlayground } from '@/components/mdx/CodePlayground';

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    // DDS components
    Callout,
    Card,
    CardGrid,
    CodeBlock,
    Collapser,
    CollapserGroup,
    Column,
    Grid,
    Heading,
    Link,
    List,
    ListItem,
    Popover,
    Table,
    TableHead,
    TableBody,
    TableRow,
    TableHeaderCell,
    TableCell,
    Tabs,
    Tab,
    TabList,
    TabPanel,
    // Custom components
    CodePlayground,
    // Pass through any additional components
    ...components,
  };
}

// Export components for direct use in the app
export {
  Callout,
  Card,
  CardGrid,
  CodeBlock,
  Collapser,
  CollapserGroup,
  Column,
  Grid,
  Heading,
  Link,
  List,
  ListItem,
  Popover,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableHeaderCell,
  TableCell,
  Tabs,
  Tab,
  TabList,
  TabPanel,
  CodePlayground,
};
